= Packages

The idea of SEU-as-code is pretty useless without software packages. Instead of
inventing somthing totally new from scratch we decided to go for a more simpler
solution. The installation of software packages using SEU-as-code is basically a
simple copy deployment. The artifacts are based on the original open source release
artifacts of the original project, spiced up with some shell scripts or some
additional customization scripts.

== Building Packages

Building packages is not hard. Again, we mainly use Gradle to build the software
packages. A good way to start is to have a look at the package builds that are
available at the https://github.com/seu-as-code/seu-as-code.packages/[SEU-as-code Packages]
GitHub repository.

Basically, the process of building your packages consists of 5 steps:

<< insert image from slides >>

The first step is usually downloading the original software package artifact from
its original site. An archive format is preferred, like ZIP, TAR or GZIP so that
it can be easily extracted in the next step. If there is no archive available,
then download the MSI or DMG or whatever, install it locally once, repackage as
archive and continue from here.

<< insert example code here >>

Next, we extract the previously downloaded artifact into the build directory. Thanks
to the power of Gradle this is an easy one using the `Copy` task type together with
the `zipTree` function.

<< insert example code here >>



== Package Repositories

Since SEU-as-code packages are basically ordinary Maven artifacts, a package repo
is required to host the packages. Most of the open source packages in the GutHub
packages repository are hosted at https://bintray.com/seu-as-code/maven/[Bintray].

TIP: Use a dedicated repository. Don't mix software packages with ordinary Maven artifacts.

But you probably soon find that you may need some customizations that are very specific
to your project or even your company. So where do you host your private software
package artifacts? You have two options.

1. *Private Company Repository:* this option is suitable for generic, company wide
artifacts you want to share. For example, we have a custom package for IntelliJ Ultimate
deployed at our repo that is used in all of our project SEUs.
So probably you also have an artifact repository server like Nexus or Artifactory
available at your company you can use.

```groovy
repositories {
  maven {
    url 'https://your.company/repo/seu-as-code'
  }
}
```

2. *Local SEU Repository:* this options is most useful for small and very SEU or
project specific artifacts and customizations. Those artifacts are part of your
SEU and should be versioned with the other SEU files.

```groovy
repositories {
  flatDir { dirs 'repo' }
}
```
