= Plugins

== Base Plugin

== Credentials Plugin

A Gradle plugin for the secure storage of your credentials either using theWindows Data Protection API (DPAPI) or the MacOS keychain mechanism. Storing any credentials in clear text in your sources or your build file is not only bad practice, it is just plain stupid since this makes it really easy for a potential attacker to access your servers and systems.

=== Basic Usage

Build script snippet for use in all Gradle versions, using the Bintray Maven repository:
[source,groovy]
----
buildscript {
    repositories {
        mavenCentral()        
        maven { url 'https://dl.bintray.com/seu-as-code/gradle-plugins' }
    }
    dependencies {
        classpath 'de.qaware.seu.as.code:seuac-credentials-plugin:2.4.0.RC1'     
    }
}

apply plugin: 'de.qaware.seu.as.code.credentials'
----

Build script snippet for new, incubating, plugin mechanism introduced in Gradle 2.1:
[source,groovy]
----
plugins {
    id 'de.qaware.seu.as.code.credentials' version '2.4.0.RC1'
}
----

=== Tasks

The plugin defines the following tasks:

[cols="1a,1a,1a,3a"]
|===
| Task name | Depends on | Type | Description

| `setCredentials`
| -
| SetCredentialsTask
| Sets the credentials for a service. Invoke with `--service [Name of service]` parameter.

| `displayCredentials`
| -
| DisplayCredentialsTask
| Displays the credentials for a service of a credential. Invoke with `--service [Name of service]` parameter.

| `clearCredentials`
| -
| ClearCredentialsTask
| Clears the credentials for a service. Invoke with `--service [Name of service]` parameter.
|===

==== Extra Properties

The plugin defines the following extra extension properties:

[cols="1a,1a,1a,3a"]
|===
| Property name | Type | Default value | Description

| `credentials`
| Credentials
| -
| Object to query credentials. Invoke the `String get(String service)` method to get the credentials with the service name `service`.
|===

==== Extension

The plugin defines the following closures in the `credentials` extension:

[cols="1a,1a,1a,3a"]
|===
| Property name | Type | Default value | Description

| `keychainFile`
| String
| `null`
| The custom location for the MacOS keychain file to use.

| `propertyFile`
| String
| `null`
| The custom location of the secure properties file under Windows.|===


=== Examples

==== Command line usage

First add the credentials for the `Nexus` service by invoking one of the following Gradle tasks, you will be asked for the username and password on the Console:
[source,shell]
----
$ ./gradlew setCredentials --service Nexus
$ ./gradlew setCredentials --service Nexus --username fooUser
----

You can also display and clear the credentials from the command line using the following Gradle tasks:[source,shell]
----
$ ./gradlew displayCredentials --service Nexus
$ ./gradlew clearCredentials --service Nexus
----

==== Using credentials in a build script

Once you have set the credentials via the command line you can then use this credential information in your build script, e.g. in the repositories section,via the `credentials` extra property:
[source,groovy]
----
repositories {
    mavenCentral()
    maven {
        url nexusUrl
        credentials { 
            // use array type access to credentials via service name 
            username project.credentials['Nexus'].username 
            password project.credentials['Nexus'].password

            // use getter access to credentials via service name 
            username project.credentials.get('Nexus').username
            password project.credentials.get('Nexus').password

            // or use string interpolation 
            username "${credentials['Nexus'].username}" 
            password "${credentials['Nexus'].password}" 
        } 
    } 
}
----

==== Custom keychain or property file location

The plugin comes with sensible default values where the credentials are stored. On MacOS this will be the user's default login keychain, and on Windows the`secure-credentials.properties` file is stored in the user's Gradle home dir. In case you want to override these locations you can define these using the`credentials` extension in your Gradle build file.
[source,groovy]
----
credentials {
    keychainFile = "$projectDir/SEU-as-code.keychain"    
    propertyFile = "$projectDir/secure-credentials.properties"
}
----

== Git Plugin

== Platform Plugin

A basic Gradle plugin that allows to apply platform specific configurations in aGradle build file. Originally, this plugin has been developed to enable multi-platform SEUs. In a mixed team you sometimes have team members that develop under Windows, MacOS or Linux. But you want to support all these platform via one Gradle build file. But usually you need to use different dependency versions between these platforms or you may require different implementations of the same task depending on the plaform.

=== Basic Usage

Build script snippet for use in all Gradle versions, using the Bintray Maven repository:

[source,groovy]
----
buildscript { 
    repositories { 
        mavenCentral() 
        maven { url 'https://dl.bintray.com/seu-as-code/gradle-plugins' } 
    } 
    
    dependencies { 
        classpath 'de.qaware.seu.as.code:seuac-platform-plugin:1.0.0' 
    }
}

apply plugin: 'de.qaware.seu.as.code.platform'
----

Build script snippet for new, incubating, plugin mechanism introduced in Gradle 2.1:

[source,groovy]
----
plugins { 
    id 'de.qaware.seu.as.code.platform' version '1.0.0'
}
----

=== Extra Properties

The plugin defines the following extra properties, that may be used for platform specific behaviour:

[cols="1a,3a"]
|===
| Task name | Description

| `osFamily`
| The OS family, either `windows`, `macos`, `unix` or `unknown`

| `osClassifier`
| The OS classifier, either `win`, `mac`, `unix` or `???`

| `osArch`
| The OS architecture, either `x86_64` or `x86`
|===

=== Extension

The plugin defines the following closures in the `platform` extension:

[cols="1a,1a,1a,3a"]
|===
| Property name | Type | Default value | Description

| `win`
| Closure
| -
| Apply configuration to project if running on Windows.

| `mac`
| Closure
| -
| Apply configuration to project if running on MacOS.

| `unix`
| Closure
| -
| Apply configuration to project if running on Linux or Unix.

| `x86`
| Closure
| -
| Apply configuration to project if running on x86 system.

| `x86_64`
| Closure
| -
| Apply configuration to project if running on x86_64 system.
|===

The following example shows the full extension configuration in code:

[source,groovy]
----
platform { 
    win { // add Windows specific code like dependencies or tasks here } 
    mac { // add MacOS specific code like dependencies or tasks here } 
    unix { // add Unix or Linux specific stuff like dependencies or tasks here } 
    x86 { // add 32-bit specific stuff like dependencies or tasks here } 
    x86_64 { // add 64-bit specific code like dependencies or tasks here }
}
----

=== Examples

==== Basic extension configuration

The following example uses the extension configuration to add platform specific dependencies as well as platform specific task definitions.

[source,groovy]
----
platform { 
    win { 
        dependencies { 
            software 'io.github.msysgit:git:1.9.5' 
            software 'org.gradle:gradle:2.13' 
        }
        task helloSeuAsCode(group: 'Example') << { 
            println 'Hello SEU-as-code on Windows.' 
        } 
    } 
    mac { 
        dependencies { 
            software 'org.gradle:gradle:2.14' 
        }
        task helloSeuAsCode(group: 'Example') << { 
            println 'Hello SEU-as-code on MacOS.' 
        } 
    }
}
----

==== Platform specific dependencies

The following example uses the `$osClassifier` extra property as classifier toadd a platform specific dependency.

[source,groovy]
----
dependencies { 
    software "de.qaware.seu.as.code:seuac-environment:2.3.0:$osClassifier"
}
----

==== Platform specific tasks

This example uses static methods from the `Platform` class to enable tasks based on the current platform the build is running on.

[source,groovy]
----
import static de.qaware.seu.as.code.plugins.platform.Platform.isWindows
import static de.qaware.seu.as.code.plugins.platform.Platform.isMacOs

task helloWorldOnWindows(group: 'Example') { 
    enabled = isWindows() 
    doLast { println 'Hello World on Windows.' }
}

task helloWorldOnlyIfMac(group: 'Example') { 
    onlyIf { isMacOs() } 
    doLast { println 'Hello World only if Mac.' }
}
----

== SVN Plugin

A Gradle plugin for handling SVN repositories. Provides basic tasks to checkout SVN repositories 
and update local directories. The repositories can be configured using an extension.

==== Basic Usage

Build script snippet for use in all Gradle versions, using the Bintray Maven repository:```groovybuildscript { repositories { mavenCentral() maven { url 'https://dl.bintray.com/seu-as-code/gradle-plugins' } } dependencies { classpath 'de.qaware.seu.as.code:seuac-svn-plugin:2.1.1' }}

apply plugin: 'de.qaware.seu.as.code.svn'```

Build script snippet for new, incubating, plugin mechanism introduced in Gradle 2.1:```groovyplugins { id 'de.qaware.seu.as.code.svn' version '2.1.1'}```

==== Tasks

The plugin defines the following tasks:

[cols="1a,1a,1a,3a"]|===| Task name | Depends on | Type | Description

| `svnCheckoutAll`| all `svnCheckout<RepositoryName>` tasks| -| Performs a SVN checkout of all defined repositories.

| `svnUpdateAll`| all `svnUpdate<RepositoryName>` tasks| -| Performs a SVN update of all defined repositories.

| `svnCheckout<RepositoryName>`| -| SvnCheckoutTask| Performs a SVN checkout of the named SVN repository.

| `svnUpdate<RepositoryName>`| -| SvnUpdateTask| Performs a SVN update of the named SVN repository.|===

==== Extension

The plugin defines the following extension properties in the `subversion` closure:

[cols="1a,1a,1a,3a"]|===| Property name | Type | Default value | Description

| `subversion`| NamedDomainObjectContainer<SvnRepository>| -| Contains the named SVN repository definitions.

| `url`| String| -| The URL of the named SVN repository.

| `directory`| File| -| The local checkout directory of the named SVN repository.

| `username`| String| -| The username used to authenticate.

| `password`| String| -| The password used to authenticate.|===

==== Examples

===== Defining SVN repositories

The following example defines the SVN repository for the SEU-as-plugins repo.The example does not hardcode the username and password properties, instead youshould use project properties or the SEU-as-code credentials plugin.

```groovysubversion { SeuAsCodePlugins { url 'https://github.com/seu-as-code/seu-as-code.plugins' directory file("$seuHome/codebase/seu-as-code.plugins/") username svnUsername password svnPassword }}```

===== Working with SVN repositories

Once you have defined one or more SVN repositories using the plugin extension,you can perform a SVN checkout and update on each repository individually or onall defined repos.

```shell$ ./gradlew svnCheckoutSeuAsCodePlugins$ ./gradlew svnUpdateAll```

