= Quickstart

If you are still reading this book than you have decided to build the SEU for your next project as-code. *Excellent choice!* The first version of your SEU is up and running in 15 minutes.
 
1. Download the latest SEU-as-code Archetype distribution from either https://bintray.com/seu-as-code/generic/seuac-archetype/_latestVersion[Bintray] or https://github.com/seu-as-code/seu-as-code.archetype/releases[GitHub].

2. Extract the archive to a custom location and rename the template project directory, e.g. `seubase`. For optimal isolation, you can use a virtual hard drive (VHD) on Windows or a sparse image disk file for Mac OSX.

3. Customize the `build.gradle` file. Adjust the `ext` configuration section and set the `seuRoot` directory path and the `seuName` accordingly. 

4. Adjust the `dependencies` section and add the desired software packages using the `software` or `home` configurations. For a complete list of available packages have a look at the https://github.com/seu-as-code/seu-as-code.packages[SEU-as-code Package] repository or the https://bintray.com/seu-as-code/maven/[Bintray] repository.

4. At this point you should add your SEU project to a version control system of your choice.

5. Finally, open a console and issue the following command to create your SEU: `gradlew bootstrapSeu`

After all artifacts have been downloaded you should have a working software development environment.